### ISSUE TITLE
Just checking Actions!

### ISSUE THREAD

**Issue by rajats98** [JJ/pr-greeting-action#12]
No issues, will close later!

**Comment by rajats98** [comment]
@JJ, No action was performed, I can see it is set up for this repo! Is there confusion? or is this build is under development, I should try on releases!

**Comment by JJ** [comment]
The problem is that it does not work if the person creating the issue is
not an owner of the project, due to the way action works.

**Comment by rajats98** [comment]
Ohh, Okay thanks, I got it!
